Labsis/LabSis CON MAURI/album/urls.py
from django.conf.urls import url
from album import views

urlpatterns = [
    url(r'^$', views.base, name='base'),
    url(r'^category/$', views.category, name='category-list'),
    url(r'^category/(?P<category_id>\d+)/detail/$', views.category_detail, name='category-detail'),
    url(r'^photo/$', views.PhotoListView.as_view(), name='photo-list'),
    url(r'^photo/(?P<pk>\d+)/detail/$', views.PhotoDetailView.as_view(), name='photo-detail'),
    # Update
    url(r'^photo/(?P<pk>\d+)/update/$', views.PhotoUpdate.as_view(), name='photo-update'),
    # Create
    url(r'^photo/create/$', views.PhotoCreate.as_view(), name='photo-create'),
    # Delete
    url(r'^photo/(?P<pk>\d+)/delete/$', views.PhotoDelete.as_view(), name='photo-delete'),
]

""" url(r'^category/$', views.category, name='category-list'),
    url(r'^category/(?P<category_id>\d+)/detail/$', views.category_detail, name='category-detail'),
    """

Labsis/LabSis CON MAURI/myapps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import album.views
import album.urls

urlpatterns = [
    url(r'^album/', include('album.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', album.views.home),
]

Labsis/LabSis CON MAURI/album/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

class Category(models.Model):
    """ Categorias para clasificar las fotos """
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Photo(models.Model):
    """ Fotos del album """
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, default='No title')
    photo = models.ImageField(upload_to='photos/')
    pub_date = models.DateField(auto_now_add=True)
    favorite = models.BooleanField(default=False)
    comment = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.title



@receiver(post_delete, sender=Photo)
def photo_delete(sender, instance, **Kwargs):
    """Borra los ficheros de las fotos que se eliminan"""
    instance.photo.delete(False)

def get_absolute_url(self):
    return reverse('photo-list')

Labsis/LabSis CON MAURI/album/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from album.models import Category, Photo
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, CreateView, DeleteView




class PhotoUpdate(UpdateView):
    model = Photo


class PhotoCreate(CreateView):
    model = Photo


class PhotoDelete(DeleteView):
    model = Photo
    success_url = reverse_lazy('photo-list')

def home(request):
    return HttpResponse('Bienvenidos a nuestra Pagina!!')

def category(request):
    category_list = Category.objects.all()
    context = {'object_list': category_list}
    return render(request, 'album/category.html', context)

def category_detail(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {'object': category}
    return render(request, 'album/category_detail.html', context)


class PhotoListView(ListView):
    model = Photo

class PhotoDetailView(DetailView):
    model = Photo

def base(request):
    return render(request, 'base.html')

Labsis/LabSis CON MAURI/album/templates/album/category.html
{% extends 'base.html' %}
{% block section %}
 <h2>Category</h2>
    <hr>
        {% endblock section %}
        {% block maincontent %}
         <div>
            <ul>
            {%for category in object_list%}
                <li> <a href="{% url 'category-detail' category.pk %}">
                    {{ category.name }}
                </a></li>
            {%endfor%}
            </ul>
        </div>
        {% endblock maincontent %}

Labsis/LabSis CON MAURI/album/templates/album/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
    <h2>{{ object.name }}</h2>
<hr>
    {% endblock section %}
    {% block maincontent %}
<div>
    <table border = "1px">
        <tr>
            {% for photo in object.photo_set.all %}
        <td>
        <div>{{ photo.title }}</div>
        <div>
            <a href="{% url 'photo-detail' photo.id %}">
                <img src="{% static photo.photo.url %}"
                style= "width:200px;height:200px"
                />
            </a>
        </div>
        </td>
        {% endfor %}
        </tr>
    </table>
</div>
{% endblock maincontent %}

Labsis/LabSis CON MAURI/album/templates/album/photo_detail.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
 <h2>
     {{ object.title }}
     {% if object.favorite %}
     &#9733;
     {% else %}
     &#9734;
     {% endif %}
    {% if object.id %}
        ( <a href="{% url 'category-detail' object.category_id %}">{{ object.category }}</a> )
    {% endif %}
 </h2>
     <p><strong>comments: </strong>{{ object.comment|default:"no comments" }}</p>
     <a href="{% url 'photo-update' object.id %}">edit</a>
     <a href="{% url 'photo-delete' object.id %}">delete</a>
<hr>
{% endblock section %}
{% block maincontent %}
<div>
    <div>
        <img src="{% static object.photo.url %}"
        style="width:550px;height:420px"/>
    </div>
</div>
{% endblock maincontent %}

Labsis/LabSis CON MAURI/album/templates/album/photo_form.html
{% extends "base.html" %}
{% block maincontent %}
<form enctype="multipart/form-data" method="post">{% csrf_token %}
     {{ form.as_p }}
     <button type="submit">Save</button>
     <a class='btn' href="{% url 'photo_list' %}">Cancel</a>
</form>
{% endblock maincontent%} 

Labsis/LabSis CON MAURI/album/templates/album/photo_list.html
<ul>
    {%for photo in object_list%}
        <li> {{photo.title}}</li>
    {%endfor%}
</ul>

Labsis/LabSis CON MAURI/album/templates/base.html
<!DOCTYPE html>
<html>
<head lang = "en">
    <meta charset="UTF-8">
    <title>Album</title>
</head>
<body>
    <h1>Album</h1>
    <ul>
        <li>
        <a href="{% url 'category-list' %}">Category</a>
        </li>
        <li>
            <a href="{% url 'photo-list' %}">Photo</a>
        </li>
    </ul>

    <hr>

    <div>
        {% block section %}
        {% endblock section %}
    </div>
    <div>
        {% block maincontent %}
        {% endblock maincontent %}
    </div>
</body>
</html>